use_frameworks!

target 'SafeBootRecord_Example' do
  pod 'SafeBootRecord', :path => '../'

  target 'SafeBootRecord_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
